package GUI;

import business.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;


public class BillUI extends JFrame {
    private JPanel BillUI;
    private JLabel Bill;
    private JButton callWaiterButton;
    private JButton onlinePaymentButton;
    private JTextPane BillInformation;
    private JButton removeBillButton;
    private Business business;
    private int tableId;
    private String BusinessName;

    public BillUI(String billDetails, int tableId, Business business, String userRole) {
        setTitle("Bill UI");
     //   setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(400, 300);
        setLocationRelativeTo(null);
        setContentPane(BillUI);
        setVisible(true);

        this.tableId = tableId;
        setBillDetails(billDetails);

        if ("worker".equals(userRole)) {
            removeBillButton.setVisible(true);
            onlinePaymentButton.setVisible(false);
            callWaiterButton.setVisible(false);
        } else {
            removeBillButton.setVisible(false);
            onlinePaymentButton.setVisible(true);
            callWaiterButton.setVisible(true);
        }


        onlinePaymentButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PaymentUI payment = new PaymentUI();
            }
        });

        callWaiterButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                createWaiterTask(tableId, business);
            }
        });
        removeBillButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                removeBill(tableId, business);
            }
        });
    }

    public void setBillDetails(String billDetails) {
        BillInformation.setText(billDetails);
    }

    private void createWaiterTask(int tableId, Business business) {
     this.business = business;
     this.tableId = tableId;
        Table table = business.getTable1(tableId);
        System.out.println(table); // Print the task details
        String description = "Waiter in table " + tableId;
        Date currentTime = new Date(); // Current date and time
        GeneralTask generalTask = new GeneralTask(description, GeneralTask.taskType.tableCall);
        generalTask.setTable(table);
        System.out.println("New Task created: " + generalTask); // Print the task details
    }

    private void removeBill(int tableId, Business business) {


        business.ordering.Bill billToRemove = business.getBill(tableId);
        if (billToRemove != null) {
            business.removeBill(billToRemove);
            Table table = business.getTable(tableId);
            if (table != null) {
                table.freeTable();
                JOptionPane.showMessageDialog(this, "Bill removed and table " + tableId + " is now available.");
            } else {
                JOptionPane.showMessageDialog(this, "Table with ID " + tableId + " not found.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No bill found for table ID: " + tableId);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        BillUI = new JPanel();
        BillUI.setLayout(new GridBagLayout());
        Bill = new JLabel();
        Bill.setText("Bill");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.gridheight = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        BillUI.add(Bill, gbc);
        onlinePaymentButton = new JButton();
        onlinePaymentButton.setText("Online Payment ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        BillUI.add(onlinePaymentButton, gbc);
        removeBillButton = new JButton();
        removeBillButton.setText("Remove bill ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        BillUI.add(removeBillButton, gbc);
        callWaiterButton = new JButton();
        callWaiterButton.setText("Call Waiter");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        BillUI.add(callWaiterButton, gbc);
        BillInformation = new JTextPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        BillUI.add(BillInformation, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return BillUI;
    }

}

