package GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CheckInUI extends JFrame {
    private JPanel CheckInUI;
    private JTextArea textArea1;
    private JButton cancelButton;
    private JButton continueButton;

    public CheckInUI() {

        setTitle("CheckIn UI");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setVisible(true);
        setLocationRelativeTo(null);
        setContentPane(CheckInUI);

        continueButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //  MenuUI MenuUi = new MenuUI();
                dispose();
            }
        });
        cancelButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                StoresUI storesUI = new StoresUI();
                dispose();
            }
        });
    }

    // Method to set the reservation details in the text area
    public void setReservationDetails(String reservationDetails) {
        textArea1.setText(reservationDetails);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        CheckInUI = new JPanel();
        CheckInUI.setLayout(new com.jgoodies.forms.layout.FormLayout("fill:d:grow,left:4dlu:noGrow,fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JLabel label1 = new JLabel();
        label1.setText("Check-In");
        com.jgoodies.forms.layout.CellConstraints cc = new com.jgoodies.forms.layout.CellConstraints();
        CheckInUI.add(label1, cc.xywh(1, 1, 3, 2));
        textArea1 = new JTextArea();
        CheckInUI.add(textArea1, cc.xyw(1, 5, 2, com.jgoodies.forms.layout.CellConstraints.FILL, com.jgoodies.forms.layout.CellConstraints.FILL));
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        CheckInUI.add(cancelButton, cc.xy(1, 7));
        continueButton = new JButton();
        continueButton.setText("Continue");
        CheckInUI.add(continueButton, cc.xy(3, 7));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return CheckInUI;
    }

}
