package GUI;

import business.Business;
import business.DineEase;
import business.Table;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class EntranceUI extends JFrame {
    private JPanel EntranceUI;
    private JTextField tableid;
    private JTextArea tableIdTextArea;
    private JTextPane numberOfPeopleTextPane;
    private JTextField numberofpeople;
    private JButton continueButton;
    private JLabel businessNameLabel;
    private int tableid1;
    private int numberofpeople1;
    private String status1;
    private JTextPane nubmerOfPeopleTextPane;

    private String Details;
    private Business business;

    public EntranceUI(Business business) {
        setTitle("EntranceUI");
       // setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setVisible(true);
        setLocationRelativeTo(null);
        setContentPane(EntranceUI);

        continueButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleContinueButton();
            }
        });
    }

    private void handleContinueButton() {

        tableid1 = Integer.parseInt(tableid.getText());
        numberofpeople1 = Integer.parseInt(numberofpeople.getText());

        Table selectedTable = null;
        Business selectedBusiness = business;


        // Search for the table by ID in the selected business
        for (Table table : selectedBusiness.getTables()) {
            if (table.getTableId() == tableid1) {
                selectedTable = table;
                break;
            }
        }


        // Check if the table is found within the business
        if (selectedTable != null) {
            // Check the number of people against the table capacity
            if (numberofpeople1 > selectedTable.getCapacity()) {
                JOptionPane.showMessageDialog(null, "The number of people exceeds the capacity of table " + tableid1 + " in " + selectedBusiness.getName() + ".");
            } else {
                // Check the status of the selected table
                if (selectedTable.getStatus() == Table.eStatus.FREE) {
                    // Change the status of the selected table
                    selectedTable.notFreeTable();

                    // Print the details of the selected table after status change
                    System.out.println("Selected Table Details (After Status Change):");
                    System.out.println(selectedTable.toString());
                    // MenuUI menuUI = new MenuUI("","","");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Table with ID " + tableid1 + " is not free in " + selectedBusiness.getName() + ".");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Table with ID " + tableid1 + " not found in " + selectedBusiness.getName() + ".");
        }

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        EntranceUI = new JPanel();
        EntranceUI.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Entrance");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        EntranceUI.add(label1, gbc);
        tableid = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        EntranceUI.add(tableid, gbc);
        tableIdTextArea = new JTextArea();
        tableIdTextArea.setText("table id :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        EntranceUI.add(tableIdTextArea, gbc);
        numberofpeople = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        EntranceUI.add(numberofpeople, gbc);
        nubmerOfPeopleTextPane = new JTextPane();
        nubmerOfPeopleTextPane.setText("nubmer of people :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        EntranceUI.add(nubmerOfPeopleTextPane, gbc);
        continueButton = new JButton();
        continueButton.setText("Continue");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        EntranceUI.add(continueButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return EntranceUI;
    }

}

