package GUI;

import business.management.CheckInOutEvent;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import users.Worker;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;

public class ScannerWorkerUI extends JFrame {
    private JPanel ScannerWorker;
    private JButton checkOutButton;
    private JButton checkInButton1;
    private Worker worker;

    public ScannerWorkerUI(Worker worker) {
        setTitle("ScannerWorkerUI");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setVisible(true);
        setLocationRelativeTo(null);
        setContentPane(ScannerWorker);




        this.worker = worker;
        checkInButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                performAction("CHECK_IN");

            }
        });
        checkOutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                performAction("CHECK_OUT");
            }
        });
    }

    public void performAction(String actionType) {
        switch (actionType.toUpperCase()) {
            case "CHECK_IN":
                performCheckInAction();
                break;
            case "CHECK_OUT":
                performCheckOutAction();
                break;
            default:

                System.out.println("Invalid action type.");
                break;
        }
    }

    private void performCheckInAction() {
        LocalDateTime checkInTime = LocalDateTime.now();
        worker.setCheckInTime(checkInTime);
        worker.setCheckInTime(checkInTime);
        CheckInOutEvent event = new CheckInOutEvent("Check-in", checkInTime);
    }

    private void performCheckOutAction() {

        LocalDateTime checkOutTime = LocalDateTime.now();
        worker.setCheckOutTime(checkOutTime);
        CheckInOutEvent event = new CheckInOutEvent("Check-Out", checkOutTime);

        // Add the event to the worker's time log
        worker.addCheckInOutEvent(event);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ScannerWorker = new JPanel();
        ScannerWorker.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        checkOutButton = new JButton();
        checkOutButton.setText("Check out ");
        ScannerWorker.add(checkOutButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        checkInButton1 = new JButton();
        checkInButton1.setText("Check In");
        ScannerWorker.add(checkInButton1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ScannerWorker;
    }
}
