package GUI;

import GUI.MenuUI;
import business.Business;
import business.Table;
import business.DineEase;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ScannerUI extends JFrame {
    private JTextField tableId;
    private JButton okButton;
    private JTextField BusinessName;
    private JPanel ScannerUI;
    int tableid1;
    String businessName1;

    public ScannerUI() {
        setTitle("Scanner UI");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setVisible(true);
        setLocationRelativeTo(null);
        setContentPane(ScannerUI);
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tableid1 = Integer.parseInt(tableId.getText());
                businessName1 = BusinessName.getText(); // Get the entered business name

                Table selectedTable = null;
                Business selectedBusiness = null;


                for (Business business : DineEase.getBusinesses()) {
                    if (business.getName().equalsIgnoreCase(businessName1)) {
                        selectedBusiness = business;


                        for (Table table : selectedBusiness.getTables()) {
                            if (table.getTableId() == tableid1) {
                                selectedTable = table;
                                break;
                            }
                        }
                        break;
                    }
                }

                if (selectedTable != null) {

                    if (selectedTable.getStatus() == Table.eStatus.FREE) {

                        selectedTable.notFreeTable();


                        System.out.println("Selected Table Details (After Status Change):");
                        System.out.println(selectedTable.toString());
                        // MenuUI menuUI = new MenuUI();

                    } else {
                        JOptionPane.showMessageDialog(null, "Table with ID " + tableid1 + " is not free in " + businessName1 + ".");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Table with ID " + tableid1 + " not found in " + businessName1 + ".");
                }
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ScannerUI = new JPanel();
        ScannerUI.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ScannerUI.add(spacer1, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Scanner");
        label1.setVerticalAlignment(1);
        label1.setVerticalTextPosition(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.NORTH;
        ScannerUI.add(label1, gbc);
        tableId = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ScannerUI.add(tableId, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("tableid");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        ScannerUI.add(label2, gbc);
        okButton = new JButton();
        okButton.setText("ok");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ScannerUI.add(okButton, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Business");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        ScannerUI.add(label3, gbc);
        BusinessName = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ScannerUI.add(BusinessName, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ScannerUI;
    }
}
