package GUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import business.Business;
import business.DineEase;
import business.ordering.Bill;

public class StoresUI extends JFrame {
    private JPanel StoresUI;
    private JButton scanButton;
    private JTextField customerNameField;
    private JScrollBar scrollBar1;
    private JButton checkOutButton;
    public String customerName;
    public String customerName1;

    public StoresUI() {
        setTitle("Stores UI");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(300, 200);
        setVisible(true);
        setLocationRelativeTo(null);
        setContentPane(StoresUI);
        // Add action listener to scanButton
        scanButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                customerName = customerNameField.getText();
                int customerId = Integer.parseInt(customerName);
               // boolean reservationFound = DineEase.reservationCheck(customerId);
                //if (!reservationFound) {
                    // No reservation found, open the scanner UI
                  //  ScannerUI scannerUI = new ScannerUI();
                }
                //dispose();
           // }
        });


        checkOutButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String customerIdText = customerNameField.getText();
                if (customerIdText.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter a customer ID.");
                    return;
                }
                try {
                    int customerId = Integer.parseInt(customerIdText);
                    Business business = findBusinessWithCustomer(customerId);
                    if (business != null) {
                        int tableId = business.getTableIdByCustomerId(customerId);
                        if (tableId != -1) {
                            Bill bill = new Bill(business.findOrderByTableId(tableId), tableId);
                            String billDetails = bill.generateBillDetails();
                            BillUI billUI = new BillUI(billDetails, tableId, business, "customer");
                        } else {
                            JOptionPane.showMessageDialog(null, "No table found for customer ID: " + customerId);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No business found with customer ID: " + customerId);
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(null, "Please enter a valid customer ID.");
                }
            }
        });

    }


    public String getCustomerName() {
        return customerName;
    }

    public String getCustomerName1() {
        return customerName1;
    }

    private Business findBusinessWithCustomer(int customerId) {
        for (Business business : DineEase.getBusinesses()) {
            if (business.hasCustomer(customerId)) {
                return business;
            }
        }
        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        StoresUI = new JPanel();
        StoresUI.setLayout(new GridBagLayout());
        scanButton = new JButton();
        scanButton.setText("Scan");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        StoresUI.add(scanButton, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Enter your reservation name :");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        StoresUI.add(label1, gbc);
        customerNameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.gridwidth = 3;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        StoresUI.add(customerNameField, gbc);
        scrollBar1 = new JScrollBar();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        StoresUI.add(scrollBar1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Stores");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTHWEST;
        StoresUI.add(label2, gbc);
        checkOutButton = new JButton();
        checkOutButton.setText("Check-out");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        StoresUI.add(checkOutButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return StoresUI;
    }

}


